import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.76.1";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface ModerateRequest {
  response_id: string;
  content: string;
  post_id: string;
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { response_id, content, post_id }: ModerateRequest = await req.json();
    
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    console.log(`🛡️ Moderando resposta ${response_id} do post ${post_id}`);

    // Buscar contexto do post original
    const { data: post } = await supabase
      .from('mural_posts')
      .select('content')
      .eq('id', post_id)
      .single();

    // Buscar configuração de prompt personalizado
    const { data: settingsData } = await supabase
      .from('settings')
      .select('value')
      .eq('key', 'mural_ai_prompt_moderation')
      .single();

    const customPrompt = settingsData?.value as string;

    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
    if (!LOVABLE_API_KEY) {
      throw new Error('LOVABLE_API_KEY não configurado');
    }

    const defaultPrompt = `Você é o GiraBot, moderador de respostas do Mural de Pedidos de Ajuda.

POST ORIGINAL:
${post?.content}

RESPOSTA A MODERAR:
${content}

Avalie se a resposta deve ser:
1. ✅ APROVADA: Útil, respeitosa, responde ao pedido de ajuda
2. ⚠️ REVISAR: Tom questionável, pode precisar ajustes
3. ❌ REJEITADA: Ofensiva, spam, fora do contexto, ou desrespeitosa

Critérios para aprovação:
- Responde ao pedido de ajuda do post original
- Tem informações úteis ou conselhos práticos
- Mantém tom profissional e respeitoso
- Não contém propaganda ou autopromoção
- Não compartilha dados sensíveis de terceiros

Responda APENAS com JSON:
{
  "approved": true/false,
  "action": "approve" | "review" | "reject",
  "reason": "explicação clara em 1 frase",
  "suggestions": "sugestões de ajuste (se action for 'review')" ou null
}`;

    const aiPrompt = customPrompt || defaultPrompt;

    const aiResponse = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${LOVABLE_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash',
        messages: [
          { role: 'system', content: 'Você é GiraBot, moderador do Mural. Responda APENAS com JSON válido.' },
          { role: 'user', content: aiPrompt.replace('${content}', content).replace('${post?.content}', post?.content || 'Post não encontrado') }
        ],
      }),
    });

    if (!aiResponse.ok) {
      console.error('AI API error:', aiResponse.status, await aiResponse.text());
      
      // Fallback: enviar para revisão manual
      await supabase
        .from('mural_responses')
        .update({ status: 'pending' })
        .eq('id', response_id);

      return new Response(
        JSON.stringify({ 
          approved: false,
          action: 'review',
          reason: 'Erro na moderação IA, enviando para revisão manual',
          suggestions: null,
          fallback: true
        }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const aiData = await aiResponse.json();
    const aiContent = aiData.choices?.[0]?.message?.content;
    
    if (!aiContent) {
      throw new Error('No content generated by AI');
    }

    // Extrair JSON da resposta
    const jsonMatch = aiContent.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      throw new Error('Invalid JSON format from AI');
    }

    const result = JSON.parse(jsonMatch[0]);
    
    console.log(`📊 Moderação: ${result.action.toUpperCase()}`);
    console.log(`📝 Razão: ${result.reason}`);

    // Atualizar status da resposta baseado na moderação
    const newStatus = result.action === 'approve' ? 'approved' : 
                      result.action === 'reject' ? 'rejected' : 'pending';

    await supabase
      .from('mural_responses')
      .update({ 
        status: newStatus,
        moderation_notes: result.reason,
        approval_source: result.action === 'approve' ? 'ai' : null,
        approved_at: result.action === 'approve' ? new Date().toISOString() : null
      })
      .eq('id', response_id);

    // Se aprovada, criar notificação para o autor do post
    if (result.action === 'approve') {
      try {
        const { data: postData } = await supabase
          .from('mural_posts')
          .select('author_id')
          .eq('id', post_id)
          .single();

        if (postData?.author_id) {
          await supabase
            .from('notifications')
            .insert({
              user_id: postData.author_id,
              title: '💬 Nova resposta no seu post',
              message: 'Alguém respondeu ao seu pedido no Mural Cresci e Perdi',
              type: 'mural_response',
              is_read: false
            });

          console.log('✅ Notificação enviada ao autor do post');
        }
      } catch (notifError) {
        console.error('Erro ao enviar notificação:', notifError);
        // Não falhar se notificação falhar
      }
    }

    console.log(`✅ Resposta ${result.action === 'approve' ? 'aprovada' : result.action === 'reject' ? 'rejeitada' : 'em revisão'}: ${response_id}`);

    return new Response(
      JSON.stringify(result),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error: any) {
    console.error('Error in mural-moderate-response:', error);
    return new Response(
      JSON.stringify({ 
        error: error.message,
        approved: false,
        action: 'review',
        reason: 'Erro no sistema, enviando para revisão manual',
        suggestions: null,
        fallback: true
      }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
