import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.76.1";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface ValidateRequest {
  title: string;
  content: string;
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { title, content }: ValidateRequest = await req.json();
    
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseKey);
    
    console.log(`✅ Validando qualidade do post: "${title}"`);

    // Buscar configurações de prompt personalizadas
    const { data: settingsData } = await supabase
      .from('settings')
      .select('value')
      .eq('key', 'mural_ai_prompt_validation')
      .single();

    const customPrompt = settingsData?.value as string;

    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
    if (!LOVABLE_API_KEY) {
      throw new Error('LOVABLE_API_KEY não configurado');
    }

    const defaultPrompt = `Você é o GiraBot, validador de qualidade do Mural Cresci e Perdi.

Analise este post e avalie sua QUALIDADE:

Título: ${title}
Conteúdo: ${content}

Critérios de qualidade:
1. ✅ APROVADO: Conteúdo construtivo, respeitoso, relevante para colaboradores
2. ⚠️ REVISAR: Conteúdo vago, muito curto (menos de 20 caracteres), ou pouco claro
3. ❌ REJEITAR: Spam, ofensivo, irrelevante, ou viola políticas da empresa

Responda APENAS com JSON:
{
  "isValid": true/false,
  "quality": "approved" | "review" | "rejected",
  "reason": "explicação clara em 1 frase",
  "suggestions": "sugestões de melhoria (se quality for 'review')" ou null
}`;

    const aiPrompt = customPrompt || defaultPrompt;

    const aiResponse = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${LOVABLE_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash',
        messages: [
          { role: 'system', content: 'Você é GiraBot, validador do Mural. Responda APENAS com JSON válido.' },
          { role: 'user', content: aiPrompt }
        ],
      }),
    });

    if (!aiResponse.ok) {
      console.error('AI API error:', aiResponse.status, await aiResponse.text());
      
      // Fallback: aprovar em caso de erro
      return new Response(
        JSON.stringify({ 
          isValid: true,
          quality: 'review',
          reason: 'Erro na validação IA, enviando para revisão manual',
          suggestions: null,
          fallback: true
        }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const aiData = await aiResponse.json();
    const aiContent = aiData.choices?.[0]?.message?.content;
    
    if (!aiContent) {
      throw new Error('No content generated by AI');
    }

    // Extrair JSON da resposta
    const jsonMatch = aiContent.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      throw new Error('Invalid JSON format from AI');
    }

    const result = JSON.parse(jsonMatch[0]);
    
    console.log(`📊 Qualidade avaliada: ${result.quality.toUpperCase()}`);
    console.log(`📝 Razão: ${result.reason}`);

    return new Response(
      JSON.stringify(result),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error: any) {
    console.error('Error in mural-ai-validate:', error);
    return new Response(
      JSON.stringify({ 
        error: error.message,
        isValid: true,
        quality: 'review',
        reason: 'Erro no sistema, enviando para revisão manual',
        suggestions: null,
        fallback: true
      }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
