import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.76.1";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface FilterRequest {
  title: string;
  content: string;
  author_id: string;
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { title, content, author_id }: FilterRequest = await req.json();
    
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    console.log(`🔍 Filtrando post do mural: "${title}" (autor: ${author_id})`);

    // Buscar posts similares recentes (últimos 30 dias) do mesmo autor
    const thirtyDaysAgo = new Date();
    thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);

    const { data: recentPosts } = await supabase
      .from('mural_posts')
      .select('title, content, created_at')
      .eq('author_id', author_id)
      .gte('created_at', thirtyDaysAgo.toISOString())
      .order('created_at', { ascending: false })
      .limit(10);

    if (!recentPosts || recentPosts.length === 0) {
      console.log('✅ Nenhum post recente encontrado, aprovando automaticamente');
      return new Response(
        JSON.stringify({ 
          isDuplicate: false,
          reason: 'Primeiro post recente do colaborador'
        }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Usar IA para detectar similaridade/duplicação
    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
    if (!LOVABLE_API_KEY) {
      throw new Error('LOVABLE_API_KEY não configurado');
    }

    const recentPostsList = recentPosts.map((p, i) => 
      `${i + 1}. "${p.title}"\n   ${p.content?.substring(0, 150)}...`
    ).join('\n\n');

    const aiPrompt = `Você é o GiraBot, moderador do Mural Cresci e Perdi.

NOVO POST:
Título: ${title}
Conteúdo: ${content}

POSTS RECENTES DO MESMO AUTOR (últimos 30 dias):
${recentPostsList}

Analise se o novo post é:
1. DUPLICADO (exatamente igual ou quase idêntico a algum post recente)
2. REPETITIVO (mesma ideia/tema mas com palavras diferentes)
3. ORIGINAL (tema novo ou abordagem diferente)

Responda APENAS com um JSON:
{
  "isDuplicate": true/false,
  "reason": "explicação clara em 1 frase",
  "similarPostIndex": número do post similar (se houver) ou null
}`;

    const aiResponse = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${LOVABLE_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash',
        messages: [
          { role: 'system', content: 'Você é GiraBot, moderador do Mural da Cresci e Perdi. Responda APENAS com JSON válido.' },
          { role: 'user', content: aiPrompt }
        ],
      }),
    });

    if (!aiResponse.ok) {
      console.error('AI API error:', aiResponse.status, await aiResponse.text());
      
      // Fallback: permitir post em caso de erro na IA
      return new Response(
        JSON.stringify({ 
          isDuplicate: false,
          reason: 'Erro na verificação IA, aprovando por segurança',
          fallback: true
        }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const aiData = await aiResponse.json();
    const aiContent = aiData.choices?.[0]?.message?.content;
    
    if (!aiContent) {
      throw new Error('No content generated by AI');
    }

    // Extrair JSON da resposta
    const jsonMatch = aiContent.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      throw new Error('Invalid JSON format from AI');
    }

    const result = JSON.parse(jsonMatch[0]);
    
    console.log(`📊 Resultado da filtragem: ${result.isDuplicate ? '❌ DUPLICADO' : '✅ ORIGINAL'}`);
    console.log(`📝 Razão: ${result.reason}`);

    return new Response(
      JSON.stringify(result),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error: any) {
    console.error('Error in mural-ai-filter:', error);
    return new Response(
      JSON.stringify({ 
        error: error.message,
        isDuplicate: false,
        reason: 'Erro no sistema, aprovando por segurança',
        fallback: true
      }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
